--Exploratory Data Analysis----

---------------1. Database Exploration----------------

---Explore All objects in the database---

SELECT *
FROM INFORMATION_SCHEMA.TABLES;

---Explore All columns in the database---

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS;



---------------2. Dimension Exploration----------------


--Explore All the countries from where customers come

SELECT DISTINCT country
FROM gold.dim_customers;

--Explore All ctaegories - Major divisons 
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1,2,3;


---------------3. Date Exploration----------------

SELECT COUNT(*)
FROM gold.dim_customers
WHERE birthdate IS NULL;  --create_date, birthdate (7439 available, 11045 not available)

SELECT TOP 2 *
FROM gold.dim_products; --start date

SELECT  *
FROM gold.fact_sales;  --Order_date, shipping_date, due_Date


--Find the date of first and last order
--How many years of sales are available

SELECT MIN(order_date) first_order_date, 
       MAX(order_date) last_order_date ,
	   DATEDIFF(year, MIN(order_date),MAX(order_date)) order_range_years,
	   DATEDIFF(month, MIN(order_date),MAX(order_date)) order_range_months
FROM gold.fact_sales;

--find youngest and oldest customer
SELECT MIN(birthdate) oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) oldest_age,
MAX(birthdate) youngest_birthdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) youngest_age
FROM gold.dim_customers;

---------------4. Measures Exploration----------------

--Find the Total Sales
SELECT SUM(sales_amount) total_sales FROM gold.fact_sales;

--Find how many items are sold

SELECT SUM(quantity) total_quantity FROM gold.fact_sales;


--Find the avg selling price
SELECT AVG(price) avg_price FROM gold.fact_sales;

--Find the Total number of orders
SELECT COUNT(order_number) total_orders FROM gold.fact_sales;

SELECT COUNT(DISTINCT order_number) total_orders FROM gold.fact_sales;

--Find the Total number of products
SELECT MAX(product_key) total_products FROM gold.dim_products;
SELECT COUNT(product_name) total_products from gold.dim_products;

--Find the total number of customers
SELECT COUNT(customer_key) FROM gold.dim_customers;


--Find the Total number of customers that have placed an order
SELECT COUNT(DISTINCT customer_key) FROM gold.fact_sales;


--Generate a report for all Key values---
SELECT 'Total Sales' measure_name , SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' measure_name , SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' measure_name , AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Toatl Nr. of Orders' measure_name , COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Toatl Nr. of Products' measure_name , COUNT(product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Toatl Nr. of Customers' measure_name , COUNT(customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Toatl Nr. of Customers placed order' measure_name , COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales


---------------5. Magnitude Analysis----------------

--Find total customers by countries

SELECT country, COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY Country
ORDER BY COUNT(customer_key) DESC;

--Find total customers by gender

SELECT gender, COUNT(customer_key) total_customers_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC;

--Find total products by categories

SELECT Category, COUNT(product_id) total_products
FROM gold.dim_products
GROUP BY Category
ORDER BY total_products DESC;


--What is the avg cost in each category

SELECT Category, AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY Category
ORDER BY avg_cost DESC ;

--What is the total revenue generated for each category?
SELECT Category, SUM(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY Category
ORDER BY total_revenue DESC;


SELECT Category, SUM(sales_amount) total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales s
ON p.product_key = s.product_key
GROUP BY Category
ORDER BY total_revenue DESC;


--Find total revenue generated by each customer

SELECT c.customer_key, c.first_name , c.last_name, SUM(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;


--What is the distribution of items sold across countries?

SELECT c.country, SUM(quantity) total_qty
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_qty DESC;


---------------6. Ranking Analysis----------------

--Which 5 products generate the highest revenue

SELECT TOP 5 product_name, SUM(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY product_name
ORDER BY total_revenue DESC;

SELECT * FROM
(
SELECT product_name, SUM(sales_amount) total_revenue,
RANK() OVER(ORDER BY SUM(sales_amount) DESC) rank_product
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY product_name)t
WHERE rank_product <= 5;


--Find 5 worst performing products in terms of sales

SELECT TOP 5 product_name, SUM(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY product_name
ORDER BY total_revenue ;

--Find 10 customers who have generated the highest revenue

SELECT * FROM
(
SELECT c.customer_key, c.first_name , c.last_name, SUM(sales_amount) total_revenue,
DENSE_RANK() OVER(ORDER BY SUM(sales_amount) DESC) rank_customers
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
) t
WHERE rank_customers <=10;


--Find 3 customes who have placed the least orders

SELECT TOP 3 c.customer_key, c.first_name , c.last_name, 
COUNT(DISTINCT order_number) total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders;